services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONPATH=/app
    command: sh -c "poetry run streamlit run seed_vault/ui/main.py & jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
