services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONPATH=/app
    command: streamlit run seismic_data/ui/main.py