name: Deploy Sphinx Docs

on:
  push:
    branches:
      - doc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies (Including Dev)
        run: |
          poetry install --with dev
          poetry run pip install -e .

      - name: Debug Python Environment
        run: |
          python -c "import sys; print('PYTHONPATH:', sys.path)"
          python -c "import seed_vault; print('✅ seed_vault found!')"

      - name: Build Docs
        run: |
          cd docs
          poetry run make clean html

      - name: Add .nojekyll File
        run: |
          touch docs/_build/html/.nojekyll

      - name: Upload Built Docs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-docs
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html
