name: Release-PyPI

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Version bump type: patch, minor, or major"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # or your preferred Python version

      - name: Install Poetry
        run: pip install poetry==2.0.1

      - name: Bump version (locally, without committing yet)
        id: bump_version
        run: |
          poetry version ${{ github.event.inputs.release_type }}
          VERSION=$(poetry version -s)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build the package
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --no-interaction

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push version bump and tag (after successful publish)
        run: |
          VERSION=${{ steps.bump_version.outputs.version }}
          git add pyproject.toml
          git commit -m "chore(release): bump version to $VERSION"
          git tag v$VERSION
          git push origin main --follow-tags
